name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discordapp.com/api/webhooks/852202281957195807/yu0qDFsPQ2h4DjRnRAkRUH4JcVDRSowy7QRiqHrJeZ9Zsd6Ajm6joxs7_tOeUOuH1zjn
        uses: Ilshidur/action-discord@master
        with:
          args: '{{ EVENT_PAYLOAD.pusher.name }} has push in the Indie Studio Repository !'
